name: Build and Test

on:
  push:
    branches:
      - main
      - gtest
  pull_request:
    branches:
      - main
      - gtest

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev
        # Build and install Google Test (if not pre-installed)
        cd /usr/src/googletest && sudo cmake . && sudo make && sudo make install

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
